### ISSUE TITLE
To parametrise some values and fix defaults.

### ISSUE THREAD

**Issue by AJRubio-Montero** [lagoproject/arti#2]
Some values are only prompted and it cannot pass them through parameters.

Needed actions:
- [x] to modify `generate_spectra.pl` to support parameters instead of promted values.

- [x] To include -x parameter to support default values without error.

- [x] to include in `do_sims.sh` some of the new parameters: "c, b, m, n, r, v, o , q" .   [ Careful, you do not include r -f (created internally by do_sims), -g , -l  (used in other do_*.sh scripts).

**Comment by rpaganmunoz** [comment]
The codes (do_sims.sh and generate_spectra.pl) have been updated for all missing parameters
